package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController// аннотация означает, что этот класс - контроллер
@RequestMapping(path="/products") // после локал хоста должен быть "демо"
public class MainController {
    @Autowired
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/rules/all") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestBody RuleTable database) {
        String name = database.getName();
        String email = database.getEmail();
        database.setName(name);
        database.setEmail(email);
        userRepository.save(database);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<RuleTable> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
