package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@RestController// аннотация означает, что этот класс - контроллер
@RequestMapping(path="/products") // после локал хоста должен быть "products"
public class MainController {
    @Autowired
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@Validated @RequestBody Products database) {
        userRepository.save(database);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Products> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
