package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@RestController// аннотация означает, что этот класс - контроллер
@RequestMapping(path="/products") // после локал хоста должен быть "products"
public class MainController {
    @Autowired
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewProduct (@Validated @RequestBody Product database) {
        System.out.println("Через Rest API получен новый продукт: " + " " + database);
        productRepository.save(database);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Product> getAllProducts() {
        return productRepository.findAll();
    }
}
